name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest torch torchvision matplotlib numpy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Train model and verify accuracy
      run: |
        python -c "from train import train_model; train_model()"
      continue-on-error: false
    
    - name: Run tests
      run: |
        pytest test_model.py -v
    
    - name: Upload augmented images
      uses: actions/upload-artifact@v4
      with:
        name: augmented-images
        path: images/
        retention-days: 30